# Generated by Django 6.1 on 2026-08-17 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Nome do Certificado')),
                ('issuing_organization', models.CharField(max_length=100, verbose_name='Organização Emissora')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='Link da Credencial')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=150, verbose_name='Curso / Formação')),
                ('institution', models.CharField(max_length=150, verbose_name='Instituição')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término (Deixe em branco se estiver cursando)')),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Tecnologia')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Título do Projeto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug da URL')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.TextField(verbose_name='Descrição curta para a listagem')),
                ('image', models.ImageField(upload_to='portfolio/images/projetos/', verbose_name='Imagem de Capa')),
                ('repository_url', models.URLField(blank=True, null=True, verbose_name='Link do Repositório')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Link do Projeto no Ar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio.technology', verbose_name='Tecnologias Utilizadas')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Seu Nome')),
                ('bio', models.TextField(verbose_name='Texto Sobre Mim')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='portfolio/images/perfil/', verbose_name='Foto de Perfil')),
                ('email', models.EmailField(max_length=255, verbose_name='Email de contato')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Link do GitHub')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Link do LinkedIn')),
                ('skills', models.ManyToManyField(related_name='skills_user', to='portfolio.technology', verbose_name='Tecnologias que utilizo')),
            ],
            options={
                'verbose_name': 'Sobre Mim',
                'verbose_name_plural': 'Sobre Mim',
            },
        ),
    ]
