# Generated by Django 6.1 on 2026-08-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/images/icons/', verbose_name='Ícone (SVG ou PNG)'),
        ),
    ]
