# Generated by Django 6.1 on 2026-08-18 12:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_technology_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ícone (SVG ou PNG)'),
        ),
    ]
