# Generated by Django 6.1 on 2026-08-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_aboutme_profile_picture_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Tecnologia', 'verbose_name_plural': 'Tecnologias'},
        ),
    ]
